// <auto-generated />
using CarInventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarInventory.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("CarInventory.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("no-image");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "no-image",
                            Make = "Toyota",
                            Model = "Camry",
                            Price = 22000m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "no-image",
                            Make = "Ford",
                            Model = "Mustang",
                            Price = 28000m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "no-image",
                            Make = "Honda",
                            Model = "Civic",
                            Price = 21500m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "no-image",
                            Make = "Tesla",
                            Model = "Model 3",
                            Price = 39000m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "no-image",
                            Make = "Chevrolet",
                            Model = "Silverado",
                            Price = 31000m,
                            Year = 2018
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "no-image",
                            Make = "Subaru",
                            Model = "Outback",
                            Price = 27800m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "no-image",
                            Make = "BMW",
                            Model = "330i",
                            Price = 33500m,
                            Year = 2019
                        });
                });

            modelBuilder.Entity("CarInventory.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "admin123",
                            Role = "Admin",
                            Username = "superadmin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
